import * as vault from './vault.js';
import {TYPES,today,dateAdd,uid,days,phase,empty,sample,validate} from './model.js';
import {download,exportCSV,exportPNG,exportZip} from './export.js';
const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=null,demo=false,page='home',selected=null,filter={q:'',manager:'',status:'',from:'',to:'',type:''},exportSettings={mask:true,notes:false,images:false},lastActivity=Date.now(),busy=false,hasVault=false;
const manager=id=>data.managers.find(m=>m.id===id)?.name||'미등록';
const person=id=>data.people.find(p=>p.id===id);
const services=id=>data.services.filter(s=>s.personId===id).sort((a,b)=>b.date.localeCompare(a.date));
const badge=(text,cls='')=>`<span class="badge ${cls}">${esc(text)}</span>`;
const btn=(text,action,id='',cls='')=>`<button class="${cls}" data-action="${action}" data-id="${esc(id)}">${text}</button>`;
const opts=(values,current='',blank='')=>(blank?`<option value="">${blank}</option>`:'')+values.map(v=>{const [id,label]=Array.isArray(v)?v:[v,v];return `<option value="${esc(id)}" ${id===current?'selected':''}>${esc(label)}</option>`}).join('');
const mgrOpts=(id='',blank='',all=false)=>opts(data.managers.filter(m=>all||m.active||m.id===id).map(m=>[m.id,m.name+(m.active?'':' (비활성)')]),id,blank);
function toast(message){$('#toast').textContent=message;$('#toast').style.display='block';clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').style.display='none',4500)}
function error(e){const area=modal.open?$('#modal-error'):$('#gate-error');if(area)area.textContent=e.message||String(e);else toast(e.message||String(e));}
function closeModal(){modal.close();modal.replaceChildren()}
function dialog(title,body,onSubmit){modal.innerHTML=`<div class="row between"><h2>${esc(title)}</h2>${btn('닫기','close','','quiet small')}</div><form id="modal-form">${body}<p id="modal-error" class="error" role="alert"></p></form>`;modal.showModal();const form=$('#modal-form');form.addEventListener('submit',async e=>{e.preventDefault();if(busy)return;busy=true;form.querySelectorAll('button[type=submit]').forEach(b=>b.disabled=true);try{await onSubmit(new FormData(form),form)}catch(e){error(e)}finally{busy=false;form.querySelectorAll('button[type=submit]').forEach(b=>b.disabled=false)}})}
const actions=(title='저장')=>`<div class="actions">${btn('취소','close')}<button type="submit" class="primary">${title}</button></div>`;
const field=(label,name,value='',type='text',required=false,full=false,max=200)=>`<label class="${full?'full':''}">${label}${required?' *':''}<input type="${type}" name="${name}" value="${esc(value)}" ${required?'required':''} maxlength="${max}"></label>`;
const area=(label,name,value='',required=false)=>`<label class="full">${label}${required?' *':''}<textarea name="${name}" maxlength="12000" ${required?'required':''}>${esc(value)}</textarea></label>`;
const val=(f,k)=>String(f.get(k)||'').trim();
async function persist(next,action){validate(next);data=demo?next:await vault.save(next,action);lastActivity=Date.now();render();toast(demo?'체험에 반영했습니다. 나가면 초기화됩니다.':'암호화 저장했습니다.');}
async function showGate(){data=null;selected=null;demo=false;page='home';filter={q:'',manager:'',status:'',from:'',to:'',type:''};$('#print-area').replaceChildren();closeModal();hasVault=await vault.exists();app.innerHTML=`<main class="gate"><section class="gate-story"><div class="brand"><b class="mark">↗</b>내일동행<span>고용서비스 사후관리</span></div><div><div class="eyebrow">CARE THAT CONTINUES</div><h1>한 사람의 내일을,<br>한 번의 지원 그 너머까지.</h1><p>상담부터 취업 후 안부까지.<br>담당자와 관리 기간, 모든 지원의 기록을<br>한곳에서 이어갑니다.</p></div><div class="story-detail">내 기기에 암호화 보관 · 증빙까지 함께 관리 · 필요한 기록만 출력</div></section><section class="gate-form"><div class="gate-card"><div class="eyebrow">MY PRIVATE WORKSPACE</div><h2>${hasVault?'다시 만나 반갑습니다':'나만의 관리 공간 시작하기'}</h2><p class="muted">${hasVault?'이 브라우저에 보관된 저장소를 열어주세요.':'자료를 보호할 저장소 암호를 정해주세요.'}</p><form id="gate-form"><label>저장소 암호<input name="password" type="password" minlength="12" maxlength="256" required autocomplete="${hasVault?'current-password':'new-password'}" placeholder="12자 이상의 암호"></label>${!hasVault?'<label>암호 확인<input name="confirm" type="password" minlength="12" maxlength="256" required autocomplete="new-password"></label>':''}<p id="gate-error" class="error" role="alert"></p><button class="primary" type="submit">${hasVault?'내 저장소 열기':'암호화 저장소 만들기'} →</button></form><div class="gate-links">${btn('가상 자료로 먼저 둘러보기','demo')}${btn('암호화 백업에서 복원','restore','','quiet')}</div><p class="fine">자료와 첨부파일은 현재 PC의 브라우저에 암호화 저장됩니다. 다른 PC와 자동 공유되지 않습니다. 암호를 잊으면 복구할 수 없으며, 브라우저 자료 삭제에 대비해 백업이 필요합니다.</p></div></section></main>`;
 $('#gate-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const f=new FormData(e.target);if(!hasVault&&f.get('password')!==f.get('confirm')){error(Error('두 암호가 일치하지 않습니다.'));return}busy=true;e.submitter.disabled=true;try{data=await vault.open(f.get('password'),!hasVault);lastActivity=Date.now();render()}catch(e){error(e)}finally{busy=false;e.submitter.disabled=false}};
}
function render(){if(!data)return;const nav=[['home','◷','관리 현황'],['people','♙','구직자 관리'],['services','≡','서비스 기록'],['managers','♧','사후관리자'],['exports','↗','출력·증빙'],['settings','⌑','보안·백업']];app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><b class="mark">↗</b>내일동행<span>고용서비스 사후관리</span></div><nav aria-label="주요 메뉴">${nav.map(([id,icon,title])=>`<button data-action="nav" data-id="${id}" class="nav ${page===id?'active':''}"><em>${icon}</em>${title}</button>`).join('')}</nav><div class="sidefoot"><strong>작은 지원도, 빠짐없이.</strong><p>내일캐쳐의 기록을 잇는<br>나만의 사후관리 공간</p><br><span class="live-dot"></span>${demo?'가상 자료 체험 중':'이 기기에 암호화 보관'}</div></aside><div class="workspace"><header class="topbar row between"><span>나의 업무 공간 <span class="muted">/ ${nav.find(x=>x[0]===page)?.[2]||''}</span></span><div class="row"><span class="muted">${today()} · ${demo?'저장되지 않는 체험':'10분 미사용 시 자동 잠금'}</span>${btn(demo?'체험 나가기':'저장소 잠금','lock','','small')}</div></header><main class="content">${demo?'<div class="notice">가상 자료 체험 중입니다. 실제 개인정보를 입력하지 마세요. 체험 내용은 저장되지 않습니다.</div>':''}${page==='home'?home():page==='people'?selected?detail():peopleView():page==='services'?serviceView():page==='managers'?managerView():page==='exports'?exportsView():settingsView()}</main></div></div>`;bindFilters();}
function title(head,sub,button=''){return `<div class="page-title row between"><div><h1>${head}</h1><p>${sub}</p></div>${button}</div>`}
function emptyBox(head,text,button=''){return `<div class="empty"><h3>${head}</h3><p>${text}</p><br>${button}</div>`}
function progress(p){const total=Math.max(1,days(p.end,p.start));const pct=Math.max(0,Math.min(100,days(today(),p.start)/total*100));return `<div class="progress"><span style="width:${pct}%"></span></div>`}
function statusBadge(p){return badge(phase(p),phase(p)==='기간 종료'?'gray':days(p.end)<=7?'amber':'')}
function home(){const active=data.people.filter(p=>phase(p)==='진행 중');const ending=active.filter(p=>days(p.end)<=14);const pending=data.services.filter(s=>s.nextDate&&!s.done).sort((a,b)=>a.nextDate.localeCompare(b.nextDate));const month=data.services.filter(s=>s.date.startsWith(today().slice(0,7)));const recent=[...data.services].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);return title('오늘도, 동행을 이어갑니다.','놓치지 말아야 할 일정과 지원 기록을 확인하세요.',btn('+ 서비스 기록','add-service','','primary'))+`<div class="stats"><div class="stat"><span>관리 중인 구직자</span><strong>${active.length}<small> 명</small></strong><small>전체 등록 ${data.people.length}명</small></div><div class="stat"><span>이번 달 고용서비스</span><strong>${month.length}<small> 건</small></strong><small>${today().slice(0,7).replace('-','년 ')}월 진행 기준</small></div><div class="stat highlight"><span>오늘까지 확인할 일정</span><strong>${pending.filter(s=>s.nextDate<=today()).length}<small> 건</small></strong><small>미완료 후속 연락 포함</small></div><div class="stat"><span>14일 이내 관리 종료</span><strong>${ending.length}<small> 명</small></strong><small>기간 연장·종료 확인</small></div></div><div class="grid-two"><section class="panel"><div class="panel-head row between"><h2>다음 동행 일정</h2>${badge('미완료 '+pending.length+'건')}</div>${pending.length?pending.slice(0,6).map(s=>`<div class="listitem"><div class="row"><div class="avatar">${esc(person(s.personId)?.name[0])}</div><div>${btn(esc(person(s.personId)?.name),'person',s.personId,'person-name')} <span class="sub">${esc(s.next||'후속 연락')}</span><div class="sub">${esc(s.type)} · ${esc(manager(s.managerId))}</div></div></div><div class="date-box">${badge(s.nextDate<today()?'기한 지남':s.nextDate===today()?'오늘':s.nextDate,s.nextDate<today()?'red':'')}<div style="margin-top:7px">${btn('완료 처리','done',s.id,'small quiet')}</div></div></div>`).join(''):emptyBox('예정된 후속 일정이 없습니다','서비스를 기록하며 다음 연락일을 지정하세요.')}</section><section class="panel"><div class="panel-head row between"><h2>관리 기간 확인</h2><small>종료 임박</small></div>${ending.length?ending.sort((a,b)=>a.end.localeCompare(b.end)).map(p=>`<div class="listitem"><div>${btn(esc(p.name),'person',p.id,'person-name')}<div class="sub">${esc(manager(p.managerId))} · ${esc(p.role||'희망 직무 미입력')}</div>${progress(p)}</div><div class="date-box">${badge('D-'+days(p.end),'amber')}<div class="sub">${p.end} 종료</div></div></div>`).join(''):emptyBox('종료가 임박한 구직자가 없습니다','관리 종료 14일 전부터 표시합니다.')}<div class="notice" style="margin:20px 0 0">관리 기간은 자동으로 연장되지 않습니다.<br>대상자와 다음 지원 계획을 확인해주세요.</div></section></div><section class="panel"><div class="panel-head row between"><h2>최근 고용서비스</h2>${btn('전체 기록 보기 →','nav','services','quiet small')}</div>${recent.length?serviceTable(recent):emptyBox('첫 번째 동행을 기록해보세요','담당자와 구직자를 등록한 뒤 지원 내용을 남길 수 있습니다.',btn('사후관리자 등록','add-manager','','primary'))}</section>`}
function peopleFiltered(){return data.people.filter(p=>(!filter.q||[p.name,p.code,p.role].join(' ').toLowerCase().includes(filter.q.toLowerCase()))&&(!filter.manager||p.managerId===filter.manager)&&(!filter.status||phase(p)===filter.status))}
function toolbar(kind){return `<div class="toolbar"><label class="grow">${kind==='people'?'구직자 검색':'구직자·내용 검색'}<input data-filter="q" value="${esc(filter.q)}" placeholder="이름, 관리번호${kind==='people'?', 희망 직무':', 지원 내용'}"></label><label>담당자<select data-filter="manager">${mgrOpts(filter.manager,'전체 담당자',true)}</select></label>${kind==='people'?`<label>관리 상태<select data-filter="status">${opts(['시작 전','진행 중','기간 종료'],filter.status,'전체 상태')}</select></label>`:`<label>서비스<select data-filter="type">${opts(TYPES,filter.type,'전체 서비스')}</select></label><label>시작일<input type="date" data-filter="from" value="${filter.from}"></label><label>종료일<input type="date" data-filter="to" value="${filter.to}"></label>`}${btn('초기화','reset','','small quiet')}</div>`}
function peopleView(){const list=peopleFiltered();return title('구직자 관리','담당자와 관리 기간, 한 사람의 지원 과정을 함께 살펴보세요.',btn('+ 구직자 등록','add-person','','primary'))+`<section class="panel">${toolbar('people')}<div class="row between panel-head"><h3>등록 구직자 <span class="muted">${list.length}명</span></h3><small>이름을 누르면 상세 기록을 볼 수 있습니다.</small></div>${list.length?`<div class="tablewrap"><table><thead><tr><th>구직자</th><th>희망 직무 / 취업 상태</th><th>사후관리자</th><th>관리 기간</th><th>진행 상태</th><th>지원</th></tr></thead><tbody>${list.map(p=>`<tr><td>${btn(esc(p.name),'person',p.id,'person-name')}<div class="sub">${esc(p.code||'관리번호 없음')}</div></td><td>${esc(p.role||'—')}<div class="sub">${esc(p.status)}</div></td><td>${esc(manager(p.managerId))}</td><td class="num">${p.start} ~ ${p.end}${progress(p)}</td><td>${statusBadge(p)}</td><td>${services(p.id).length}건</td></tr>`).join('')}</tbody></table></div>`:emptyBox(data.people.length?'조건에 맞는 구직자가 없습니다':'등록된 구직자가 없습니다','사후관리자를 먼저 등록하고 구직자의 관리 기간을 설정하세요.',btn('+ 구직자 등록','add-person','','primary'))}</section>`}
function detail(){const p=person(selected);if(!p){selected=null;return peopleView()}const list=services(p.id);return `<div style="margin-bottom:18px">${btn('← 구직자 목록','back','','quiet small')}</div>`+title(`${esc(p.name)} <span style="vertical-align:middle">${statusBadge(p)}</span>`,`${esc(p.code||'관리번호 미입력')} · ${esc(p.role||'희망 직무 미입력')}`,`<div class="row">${btn('정보 수정','edit-person',p.id)}${btn('+ 서비스 기록','add-service',p.id,'primary')}</div>`)+`<div class="detail-grid"><aside><section class="panel"><h3>관리 정보</h3><dl class="facts"><dt>사후관리자</dt><dd>${esc(manager(p.managerId))}</dd><dt>전체 관리 기간</dt><dd>${p.start}<br>~ ${p.end}${progress(p)}</dd><dt>남은 기간</dt><dd>${phase(p)==='시작 전'?'시작까지 '+days(p.start)+'일':days(p.end)<0?'관리 기간 종료':days(p.end)+'일'}</dd><dt>연락처</dt><dd>${esc(p.phone||'—')}</dd><dt>취업 상태</dt><dd>${esc(p.status)}</dd><dt>관리 메모</dt><dd class="pre">${esc(p.note||'—')}</dd></dl></section><section class="panel"><h3>이전 담당·기간 설정</h3>${p.history.length?p.history.slice().reverse().map(h=>`<div class="listitem"><div>${esc(manager(h.managerId))}<div class="sub">${h.start} ~ ${h.end}</div><div class="sub">변경 기록 ${esc(h.at.slice(0,10))}</div></div></div>`).join(''):'<p class="sub">아직 변경 이력이 없습니다.</p>'}</section>${btn('구직자 삭제','delete-person',p.id,'quiet danger small')}</aside><section><div class="row between panel-head"><h2>지원 타임라인 <span class="muted">${list.length}</span></h2>${btn('이 구직자 출력','export-person',p.id,'small')}</div>${list.length?`<div class="timeline">${list.map(eventCard).join('')}</div>`:`<section class="panel">${emptyBox('아직 지원 기록이 없습니다','실제로 진행한 상담·컨설팅·정보 제공을 기록해보세요.')}</section>`}</section></div>`}
function eventCard(s){const p=person(s.personId);return `<article class="event"><div class="sub" style="margin-bottom:10px">${s.date} · ${esc(manager(s.managerId))} · ${esc(s.method)}</div><div class="event-card"><div class="row between"><h3>${esc(s.type)}</h3><div>${btn('수정','edit-service',s.id,'small quiet')}${btn('삭제','delete-service',s.id,'small quiet danger')}</div></div>${s.date<p.start||s.date>p.end?'<div class="sub">현재 설정된 관리 기간 외의 기록</div>':''}<div class="event-body pre">${esc(s.content)}</div>${s.result?`<div class="sub pre"><b>진행 결과</b><br>${esc(s.result)}</div>`:''}${s.nextDate||s.next?`<div class="notice" style="margin:15px 0 0"><div class="row between"><span>다음 조치 · ${esc(s.next||'후속 연락')} ${esc(s.nextDate)}</span>${s.done?badge('완료'):s.nextDate?btn('완료 처리','done',s.id,'small'):''}</div></div>`:''}<div class="chips">${s.files.map(f=>btn('⌁ '+esc(f.name),'file',s.id+'|'+f.id,'small')).join('')}</div></div></article>`}
function filteredServices(){return [...data.services].filter(s=>{const p=person(s.personId);return(!filter.q||[p?.name,p?.code,s.content,s.result].join(' ').toLowerCase().includes(filter.q.toLowerCase()))&&(!filter.manager||s.managerId===filter.manager)&&(!filter.type||s.type===filter.type)&&(!filter.from||s.date>=filter.from)&&(!filter.to||s.date<=filter.to)}).sort((a,b)=>b.date.localeCompare(a.date))}
function serviceTable(list){return `<div class="tablewrap"><table><thead><tr><th>진행일</th><th>구직자</th><th>서비스 / 내용</th><th>진행 담당자</th><th>후속 일정</th><th>증빙</th></tr></thead><tbody>${list.map(s=>`<tr><td class="num">${s.date}</td><td>${btn(esc(person(s.personId)?.name),'person',s.personId,'person-name')}</td><td>${btn(esc(s.type),'edit-service',s.id,'person-name')}<div class="sub">${esc(s.content.slice(0,55))}${s.content.length>55?'…':''}</div></td><td>${esc(manager(s.managerId))}</td><td>${s.nextDate||'—'}${s.done?'<div>'+badge('완료')+'</div>':''}</td><td>${s.files.length}개</td></tr>`).join('')}</tbody></table></div>`}
function serviceView(){const list=filteredServices();return title('서비스 기록','실제로 진행한 지원과 후속 조치를 날짜별로 남겨주세요.',btn('+ 서비스 기록','add-service','','primary'))+`<section class="panel">${toolbar('services')}<h3 class="panel-head">조회 기록 <span class="muted">${list.length}건</span></h3>${list.length?serviceTable(list):emptyBox('표시할 서비스 기록이 없습니다','조건을 바꾸거나 새로운 지원 기록을 등록하세요.')}</section>`}
function managerView(){return title('사후관리자','내 저장소에서 사용할 담당자 명부입니다. 로그인 계정이나 공유 권한은 생성되지 않습니다.',btn('+ 사후관리자 등록','add-manager','','primary'))+`<section class="panel"><h2>담당자 ${data.managers.length}명</h2>${data.managers.length?data.managers.map(m=>`<div class="manager-card"><div class="row"><div class="avatar">${esc(m.name[0])}</div><div><h3>${esc(m.name)} ${!m.active?badge('비활성','gray'):''}</h3><div class="sub">${esc(m.org||'소속 미입력')} · ${esc(m.phone||'연락처 미입력')}</div></div></div><div class="row"><small>담당 구직자 ${data.people.filter(p=>p.managerId===m.id).length}명</small>${btn('수정','edit-manager',m.id,'small')}</div></div>`).join(''):emptyBox('첫 사후관리자를 등록하세요','담당자 등록 → 구직자 등록 → 서비스 기록 순서로 시작합니다.')}</section>`}
function managerForm(id){const m=data.managers.find(m=>m.id===id)||{name:'',org:'',phone:'',active:true};dialog(id?'사후관리자 수정':'사후관리자 등록',`<div class="form-grid">${field('이름','name',m.name,'text',true,false,100)}${field('소속','org',m.org)}${field('연락처','phone',m.phone,'tel',false,false,100)}<label>사용 여부<select name="active">${opts([['yes','사용'],['no','비활성']],m.active?'yes':'no')}</select></label></div><p class="sub">비활성 처리해도 과거 지원 기록과 담당 이력은 유지됩니다.</p>${actions()}`,async f=>{const next=structuredClone(data),record={id:id||uid(),name:val(f,'name'),org:val(f,'org'),phone:val(f,'phone'),active:f.get('active')==='yes'};const i=next.managers.findIndex(x=>x.id===id);if(i<0)next.managers.push(record);else next.managers[i]=record;await persist(next,'담당자 저장');closeModal()})}
function personForm(id){if(!data.managers.some(m=>m.active)&&!id){toast('먼저 사용 중인 사후관리자를 등록해주세요.');page='managers';render();managerForm();return}const p=person(id)||{name:'',code:'',phone:'',role:'',status:'구직 중',managerId:data.managers.find(m=>m.active)?.id,start:today(),end:dateAdd(90),note:'',history:[]};dialog(id?'구직자 정보 수정':'구직자 등록',`<div class="form-grid">${field('이름','name',p.name,'text',true,false,100)}${field('관리번호','code',p.code,'text',false,false,100)}${field('연락처','phone',p.phone,'tel',false,false,100)}${field('희망 직무','role',p.role)}<label>사후관리자 *<select name="managerId" required>${mgrOpts(p.managerId)}</select></label><label>취업 상태<select name="status">${opts(['구직 중','입사 예정','취업 후 관리','지원 보류','종결'],p.status)}</select></label>${field('관리 시작일','start',p.start,'date',true)}${field('관리 종료일','end',p.end,'date',true)}${area('관리 메모 · 필요한 내용만 입력','note',p.note)}</div><p class="sub">담당자 또는 관리 기간을 바꾸면 이전 설정이 이력으로 보관됩니다.</p>${actions()}`,async f=>{const record={...p,id:id||uid(),...Object.fromEntries(['name','code','phone','role','managerId','start','end','status','note'].map(k=>[k,val(f,k)]))};if(record.start>record.end)throw Error('종료일은 시작일 이후여야 합니다.');if(record.code&&data.people.some(x=>x.id!==id&&x.code===record.code))throw Error('이미 사용 중인 관리번호입니다.');if(id&&['managerId','start','end'].some(k=>p[k]!==record[k]))record.history=[...p.history,{managerId:p.managerId,start:p.start,end:p.end,at:new Date().toISOString()}];const next=structuredClone(data),i=next.people.findIndex(x=>x.id===id);if(i<0)next.people.push(record);else next.people[i]=record;await persist(next,'구직자 저장');closeModal()})}
async function fileRead(file){if(file.size>3*1024*1024)throw Error('파일 한 개는 3MB 이하여야 합니다.');if(!/\.(png|jpe?g|pdf|docx|hwp|hwpx)$/i.test(file.name))throw Error('PNG, JPG, PDF, DOCX, HWP, HWPX 파일을 선택하세요.');const bytes=new Uint8Array(await file.arrayBuffer());const png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71;const jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255;const mime=png?'image/png':jpg?'image/jpeg':'application/octet-stream';let str='';for(let i=0;i<bytes.length;i+=8192)str+=String.fromCharCode(...bytes.subarray(i,i+8192));return{id:uid(),name:file.name,data:'data:'+mime+';base64,'+btoa(str)}}
function serviceForm(id,pid){if(!data.people.length){toast('먼저 구직자를 등록해주세요.');personForm();return}const s=data.services.find(s=>s.id===id)||{personId:pid||data.people[0].id,managerId:person(pid||data.people[0].id).managerId,date:today(),type:TYPES[0],method:'대면',content:'',result:'',next:'',nextDate:'',done:false,files:[]};dialog(id?'서비스 기록 수정':'서비스 기록 추가',`<div class="form-grid"><label>구직자 *<select name="personId" required>${opts(data.people.map(p=>[p.id,p.name+' · '+(p.code||p.role||'관리번호 없음')]),s.personId)}</select></label><label>실제 진행 담당자 *<select name="managerId" required>${mgrOpts(s.managerId)}</select></label>${field('진행일','date',s.date,'date',true)}<label>서비스 종류<select name="type">${opts(TYPES,s.type)}</select></label><label>진행 방법<select name="method">${opts(['대면','전화','문자·메신저','이메일','화상','기타'],s.method)}</select></label><div></div>${area('지원 내용','content',s.content,true)}${area('진행 결과','result',s.result)}${field('다음 조치','next',s.next)}${field('다음 연락일','nextDate',s.nextDate,'date')}<label class="checkline full"><input type="checkbox" name="done" ${s.done?'checked':''}>후속 조치 완료</label><label class="full">증빙 파일 추가 · 각 3MB, 기록당 10개 이내<input type="file" name="files" accept=".png,.jpg,.jpeg,.pdf,.docx,.hwp,.hwpx" multiple></label>${s.files.length?`<div class="full">${s.files.map(f=>`<label class="checkline"><input type="checkbox" name="removeFiles" value="${esc(f.id)}">삭제: ${esc(f.name)}</label>`).join('')}</div>`:''}</div><p class="sub">파일은 내용과 함께 암호화됩니다. 전체 증빙은 약 30MB까지 보관할 수 있습니다.<br>관리 기간 밖의 지원도 저장할 수 있으며 상세 화면에 표시됩니다.</p>${actions()}`,async(f,form)=>{const files=[...s.files.filter(x=>!f.getAll('removeFiles').includes(x.id))];for(const file of form.elements.files.files)files.push(await fileRead(file));const record={id:id||uid(),...Object.fromEntries(['personId','managerId','date','type','method','content','result','next','nextDate'].map(k=>[k,val(f,k)])),done:f.has('done'),files};if(record.nextDate&&record.nextDate<record.date)throw Error('다음 연락일은 진행일 이후로 지정하세요.');if(record.date>today())throw Error('실제 진행한 서비스만 기록해주세요. 향후 일정은 다음 연락일에 입력하세요.');const next=structuredClone(data),i=next.services.findIndex(x=>x.id===id);if(i<0)next.services.push(record);else next.services[i]=record;await persist(next,'서비스 저장');closeModal()});$('#modal-form').elements.personId.onchange=e=>{const pid=e.target.value;$('#modal-form').elements.managerId.value=person(pid).managerId};}
let exportPerson='';
function exportList(){return filteredServices().filter(s=>!exportPerson||s.personId===exportPerson)}
function exportsView(){const list=exportList();return title('출력·증빙','대상과 기간을 고르고, 필요한 기록을 한 번에 꺼내세요.')+`<section class="panel">${toolbar('services')}<label style="max-width:330px">출력 대상<select id="export-person">${opts(data.people.map(p=>[p.id,p.name+' · '+(p.code||'관리번호 없음')]),exportPerson,'전체 구직자')}</select></label><div class="row" style="margin:20px 0"><label class="checkline"><input type="checkbox" data-export="mask" ${exportSettings.mask?'checked':''}>이름·연락처 가리기</label><label class="checkline"><input type="checkbox" data-export="notes" ${exportSettings.notes?'checked':''}>상세 상담 내용 포함</label><label class="checkline"><input type="checkbox" data-export="images" ${exportSettings.images?'checked':''}>PDF에 증빙 이미지 포함</label></div><div class="notice">내려받은 파일에는 저장소 암호가 적용되지 않습니다. 이름 가리기는 기본 인적사항에만 적용되며, 자유 입력 내용·첨부 이미지·원본 파일 속 개인정보는 직접 확인해주세요. 증빙 묶음에는 원본이 포함됩니다.</div><div class="row">${btn('인쇄 / PDF 저장','print','','primary')}${btn('CSV 내려받기','csv')}${btn('진행 요약 PNG','png')}${btn('증빙 원본 ZIP','zip')}</div></section><section class="panel"><div class="panel-head row between"><h2>출력 미리보기</h2>${badge(list.length+'건 선택')}</div><div id="report-preview">${reportHTML(list)}</div></section>`}
function nameFor(p){return exportSettings.mask?p.name[0]+'○'.repeat(Math.max(1,p.name.length-1)):p.name}
function reportHTML(list){const pids=exportPerson?[exportPerson]:[...new Set(list.map(s=>s.personId))];return `<div class="report"><div class="report-top"><div class="eyebrow">NAEIL CARE RECORD</div><h1>고용서비스 사후관리 기록</h1><p class="sub">진행일 기준 ${esc(filter.from||'전체')} ~ ${esc(filter.to||'전체')} · 작성일 ${today()} · ${list.length}건${demo?' · 가상 체험 자료':''}</p></div>${pids.length?pids.map(pid=>{const p=person(pid),records=list.filter(s=>s.personId===pid);return `<section class="report-section"><h2>${esc(nameFor(p))} ${exportSettings.mask?'':`<small>${esc(p.code)}</small>`}</h2><p class="sub">현재 사후관리자 ${esc(manager(p.managerId))} · 관리 기간 ${p.start} ~ ${p.end}<br>희망 직무 ${esc(p.role||'—')} · 취업 상태 ${esc(p.status)}${!exportSettings.mask?' · 연락처 '+esc(p.phone||'—'):''}</p><table><thead><tr><th style="width:16%">진행일</th><th style="width:21%">서비스</th><th style="width:16%">진행 담당자</th><th>진행 결과 / 후속 조치</th></tr></thead><tbody>${records.map(s=>`<tr><td>${s.date}</td><td>${esc(s.type)}<br><small>${esc(s.method)} · 증빙 ${s.files.length}개</small></td><td>${esc(manager(s.managerId))}</td><td>${exportSettings.notes?`<div class="pre">${esc(s.content)}<br>${esc(s.result)}</div>`:'상세 내용 생략'}<div class="sub">${esc(s.nextDate)} ${exportSettings.notes?esc(s.next):''} ${s.done?'완료':''}</div></td></tr>${exportSettings.images?s.files.filter(f=>/^data:image\//.test(f.data)).map(f=>`<tr><td colspan="4"><img alt="첨부 증빙" src="${f.data}"><div class="sub">첨부 증빙 이미지</div></td></tr>`).join(''):''}`).join('')}</tbody></table>${!records.length?'<p class="sub">선택 기간의 기록이 없습니다.</p>':''}</section>`}).join(''):'<p class="empty">선택된 기록이 없습니다.</p>'}<footer>내일동행 · 입력 기록을 정리한 자료이며, 실제 서비스 수행을 별도로 인증하는 문서는 아닙니다.</footer></div>`}
function settingsView(){return title('보안·백업','내 기기에 보관하는 자료는 정기적으로 백업해주세요.')+`<div class="grid-two"><section class="panel"><h2>암호화 백업</h2><p class="muted" style="margin:15px 0 22px">구직자, 담당자, 서비스 기록과 첨부파일을<br>하나의 암호화 파일로 보관합니다.</p><div class="row">${btn('암호화 백업 다운로드','backup','','primary')}${btn('백업 복원','restore')}</div><p class="sub" style="margin-top:18px">복원 시 현재 자료 전체를 백업 내용으로 교체합니다.<br>백업에 사용한 암호로 복원하며, 복원 후에도 해당 암호를 사용합니다.</p></section><section class="panel"><h2>저장소 보호</h2><dl class="facts"><dt>보관 위치</dt><dd>현재 브라우저의 IndexedDB · AES-256-GCM 암호화</dd><dt>암호 처리</dt><dd>PBKDF2-SHA256 · 600,000회</dd><dt>자동 잠금</dt><dd>10분간 사용하지 않으면 잠금</dd><dt>동시 사용</dt><dd>동일 저장소는 한 번에 한 탭에서 사용</dd></dl></section></div><section class="panel"><h2>처음 사용하는 분께</h2><ol class="help-list"><li><b>사후관리자</b>에서 담당자를 등록합니다. 담당자 명부이며 별도 로그인 계정은 아닙니다.</li><li><b>구직자 관리</b>에서 담당자와 시작일·종료일을 지정합니다.</li><li><b>서비스 기록</b>에 실제 지원 내용과 다음 연락일, 증빙 파일을 남깁니다.</li><li><b>출력·증빙</b>에서 대상자·기간·서비스를 선택하고 미리보기를 확인한 뒤 내보냅니다. PDF는 인쇄 창에서 ‘PDF로 저장’을 선택합니다.</li><li>사용 후 <b>암호화 백업</b>을 받고 저장소를 잠급니다. 브라우저 자료가 삭제되거나 암호를 잊으면 원본을 복구할 수 없습니다.</li></ol><p class="notice">같은 주소라도 PC·브라우저 프로필마다 자료가 따로 보관됩니다. 브라우저 저장소 암호화는 열려 있는 화면, 다운로드한 문서, 기기 자체의 보안을 대신하지 않습니다.</p></section><section class="panel"><h2>최근 저장 이력</h2><p class="sub">로컬 작업 참고용 기록이며, 위변조를 방지하는 공식 감사 로그가 아닙니다.</p>${data.audit.slice(-10).reverse().map(a=>`<div class="listitem"><span>${esc(a.action)}</span><small>${esc(new Date(a.at).toLocaleString('ko-KR'))}</small></div>`).join('')||'<p class="sub">아직 저장 이력이 없습니다.</p>'}</section>`}
function bindFilters(){document.querySelectorAll('[data-filter]').forEach(el=>{el.onchange=()=>{filter[el.dataset.filter]=el.value;render()}});const ep=$('#export-person');if(ep)ep.onchange=()=>{exportPerson=ep.value;render()};document.querySelectorAll('[data-export]').forEach(el=>{el.onchange=()=>{exportSettings[el.dataset.export]=el.checked;render()}})}
function confirmDialog(title,body,run,label='확인'){dialog(title,`<p style="margin-top:20px">${body}</p>${actions(label)}`,async()=>{await run();closeModal()})}
function restoreForm(){if(demo){toast('체험을 나간 뒤 백업을 복원해주세요.');return}dialog('암호화 백업 복원',`<p class="sub" style="margin-top:15px">현재 저장소가 있으면 전체 자료가 교체됩니다. 필요한 자료는 먼저 백업해주세요.</p><div class="form-grid"><label class="full">내일동행 백업 파일<input type="file" name="backup" accept=".json" required></label><label class="full">백업을 만들 때 사용한 암호<input type="password" name="password" minlength="12" maxlength="256" required autocomplete="off"></label><label class="checkline full"><input type="checkbox" name="agree" required>현재 자료를 교체하고, 백업의 암호를 사용하는 것을 확인했습니다.</label></div>${actions('확인 후 복원')}`,async(f,form)=>{const file=form.elements.backup.files[0];if(!file||file.size>70000000)throw Error('70MB 이하의 내일동행 백업 파일을 선택하세요.');const content=JSON.parse(await file.text());data=await vault.restore(content,f.get('password'));demo=false;page='home';selected=null;lastActivity=Date.now();closeModal();render();toast('복원했습니다. 이제 백업의 암호를 사용하세요.');})}
async function lockNow(){if(busy)return;busy=true;try{await vault.lock();await showGate();toast('저장소를 잠갔습니다.')}finally{busy=false}}
document.addEventListener('click',async e=>{const target=e.target.closest('[data-action]');if(!target)return;e.preventDefault();if(busy)return;const action=target.dataset.action,id=target.dataset.id;try{
 if(action==='close'){closeModal();return}
 if(action==='demo'){data=sample();demo=true;page='home';lastActivity=Date.now();render();return}
 if(action==='restore'){restoreForm();return}
 if(action==='lock'){await lockNow();return}
 if(!data)return;
 if(action==='nav'){page=id;selected=null;filter={q:'',manager:'',status:'',from:'',to:'',type:''};exportPerson='';render()}
 if(action==='reset'){filter={q:'',manager:'',status:'',from:'',to:'',type:''};render()}
 if(action==='person'){page='people';selected=id;render()}
 if(action==='back'){selected=null;render()}
 if(action==='add-manager'||action==='edit-manager')managerForm(id||undefined);
 if(action==='add-person'||action==='edit-person')personForm(id||undefined);
 if(action==='add-service')serviceForm(undefined,id||undefined);
 if(action==='edit-service')serviceForm(id);
 if(action==='done'){const next=structuredClone(data);next.services.find(s=>s.id===id).done=true;busy=true;try{await persist(next,'후속 조치 완료')}finally{busy=false}}
 if(action==='delete-service')confirmDialog('서비스 기록 삭제','연결된 증빙 파일도 함께 삭제됩니다. 삭제할까요?',async()=>{const next=structuredClone(data);next.services=next.services.filter(s=>s.id!==id);await persist(next,'서비스 삭제')},'삭제');
 if(action==='delete-person'){if(services(id).length)throw Error('지원 기록이 연결되어 있습니다. 서비스 기록을 먼저 정리한 뒤 삭제해주세요.');confirmDialog('구직자 삭제','이 구직자의 기본정보와 담당 배정 이력을 삭제할까요?',async()=>{const next=structuredClone(data);next.people=next.people.filter(p=>p.id!==id);selected=null;await persist(next,'구직자 삭제')},'삭제')}
 if(action==='file'){const [sid,fid]=id.split('|'),f=data.services.find(s=>s.id===sid).files.find(f=>f.id===fid);dialog('증빙 파일',`<p class="sub" style="margin:15px 0">${esc(f.name)}</p>${/^data:image\//.test(f.data)?`<img src="${f.data}" class="filepreview" alt="첨부 증빙">`:'<p>문서는 내려받아 확인할 수 있습니다.</p>'}<p class="sub">내려받은 원본은 암호화되지 않습니다.</p>${actions('원본 다운로드')}`,async()=>{download(f.name,dataBlob(f.data));closeModal()})}
 if(action==='export-person'){page='exports';exportPerson=id;filter={q:'',manager:'',status:'',from:'',to:'',type:''};render()}
 if(action==='backup'){if(demo)throw Error('체험 자료는 백업하지 않습니다. 저장소를 만든 뒤 사용해주세요.');download('내일동행-암호화백업-'+today()+'.json',new Blob([JSON.stringify(await vault.backup())],{type:'application/json'}));toast('암호화 백업을 내려받았습니다.')}
 if(['print','csv','png','zip'].includes(action)){const list=exportList();if(!list.length)throw Error('내보낼 서비스 기록을 먼저 선택해주세요.');if(filter.from&&filter.to&&filter.from>filter.to)throw Error('조회 시작일과 종료일을 확인해주세요.');if(action==='print'){const pr=$('#print-area');pr.innerHTML=reportHTML(list);await Promise.all([...pr.querySelectorAll('img')].map(i=>i.decode().catch(()=>{})));window.print();}if(action==='csv')exportCSV(list,data,exportSettings,manager,nameFor);if(action==='png')await exportPNG(list,data,exportSettings,manager,nameFor);if(action==='zip')confirmDialog('증빙 원본 묶음 내려받기','선택된 기록의 원본 증빙 파일을 ZIP으로 저장합니다. 이름 가림이 원본 파일에는 적용되지 않습니다. 내용을 확인하셨나요?',async()=>{exportZip(list,data);toast('원본 증빙 묶음을 내려받았습니다.')},'원본 ZIP 다운로드');}
 }catch(e){error(e)}});
function dataBlob(url){const raw=atob(url.split(',')[1]);return new Blob([Uint8Array.from(raw,c=>c.charCodeAt(0))],{type:url.split(':')[1].split(';')[0]})}
['pointerdown','keydown','input'].forEach(event=>document.addEventListener(event,()=>{lastActivity=Date.now()},{passive:true}));
setInterval(()=>{if(data&&!busy&&Date.now()-lastActivity>=600000)lockNow().catch(error)},10000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&data&&Date.now()-lastActivity>=600000)lockNow().catch(error)});
window.addEventListener('afterprint',()=>$('#print-area').replaceChildren());
modal.addEventListener('cancel',e=>{if(busy)e.preventDefault();else setTimeout(()=>modal.replaceChildren(),0)});
showGate().catch(e=>{app.innerHTML=`<main class="content"><h1>저장소를 열 수 없습니다</h1><p>${esc(e.message)}</p><p>최신 Chrome 또는 Edge의 일반 창에서 다시 시도해주세요.</p></main>`});
