import {empty,validate} from './model.js';
const enc=new TextEncoder(),dec=new TextDecoder();let key=null,salt=null,current=null,release=null;let queue=Promise.resolve();
const b64=a=>{let s='';for(let i=0;i<a.length;i+=8192)s+=String.fromCharCode(...a.subarray(i,i+8192));return btoa(s)};
const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
let dbPromise;function db(){return dbPromise??=new Promise((resolve,reject)=>{const r=indexedDB.open('naeil-aftercare-v1',1);r.onupgradeneeded=()=>r.result.createObjectStore('vault');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('브라우저 저장소를 열 수 없습니다. 일반 Chrome 또는 Edge 창에서 다시 시도하세요.'))})}
async function read(){const d=await db();return new Promise((resolve,reject)=>{const r=d.transaction('vault').objectStore('vault').get('main');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(Error('저장소 읽기 실패'))})}
async function write(e){const d=await db();return new Promise((resolve,reject)=>{const tx=d.transaction('vault','readwrite');tx.objectStore('vault').put(e,'main');tx.oncomplete=resolve;tx.onerror=()=>reject(Error('저장 실패: 기기 저장 공간을 확인하세요. 기존 자료는 유지됩니다.'));tx.onabort=()=>reject(Error('저장 작업이 취소되었습니다.'))})}
async function derive(password,s){const raw=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveKey']);return crypto.subtle.deriveKey({name:'PBKDF2',hash:'SHA-256',iterations:600000,salt:s},raw,{name:'AES-GCM',length:256},false,['encrypt','decrypt'])}
async function encrypt(data,k=key,s=salt){const iv=crypto.getRandomValues(new Uint8Array(12));return{format:'naeil-aftercare-v1',iterations:600000,salt:b64(s),iv:b64(iv),data:b64(new Uint8Array(await crypto.subtle.encrypt({name:'AES-GCM',iv},k,enc.encode(JSON.stringify(data)))))}}
async function decrypt(e,password){if(e?.format!=='naeil-aftercare-v1'||e.iterations!==600000||typeof e.data!=='string'||e.data.length>70000000)throw Error('내일동행 암호화 백업 파일을 선택하세요.');const s=bytes(e.salt),iv=bytes(e.iv);if(s.length!==16||iv.length!==12)throw Error('백업 형식이 올바르지 않습니다.');const k=await derive(password,s);let data;try{data=JSON.parse(dec.decode(await crypto.subtle.decrypt({name:'AES-GCM',iv},k,bytes(e.data))))}catch{throw Error('암호가 맞지 않거나 파일이 손상되었습니다.')}return{data:validate(data),key:k,salt:s}}
async function acquire(){if(release)return;if(!navigator.locks)throw Error('이 브라우저는 안전한 동시 사용 제어를 지원하지 않습니다. Chrome 또는 Edge를 사용하세요.');await new Promise((resolve,reject)=>navigator.locks.request('naeil-aftercare-open',{ifAvailable:true},async lock=>{if(!lock){reject(Error('다른 탭에서 열려 있습니다. 먼저 그 탭의 저장소를 잠가주세요.'));return}await new Promise(done=>{release=done;resolve()})}).catch(reject))}
function serial(fn){const job=queue.then(fn);queue=job.catch(()=>{});return job}
export const exists=async()=>!!await read();
let tries=0,until=0;
export const open=(password,create=false)=>serial(async()=>{if(Date.now()<until)throw Error('시도 횟수가 많습니다. 1분 후 다시 시도하세요.');if(password.length<12||password.length>256)throw Error('암호는 12~256자로 입력하세요.');await acquire();try{const e=await read();if(create&&e)throw Error('이미 저장소가 있습니다. 기존 암호로 열어주세요.');if(!create&&!e)throw Error('먼저 저장소를 만들어주세요.');if(e){const r=await decrypt(e,password);key=r.key;salt=r.salt;current=r.data}else{salt=crypto.getRandomValues(new Uint8Array(16));key=await derive(password,salt);current=empty();await write(await encrypt(current))}tries=0;return structuredClone(current)}catch(e){key=null;current=null;salt=null;release?.();release=null;if(++tries>=5){until=Date.now()+60000;tries=0}throw e}});
export const save=(data,action)=>serial(async()=>{if(!key)throw Error('저장소를 먼저 열어주세요.');const next=validate(structuredClone(data));next.audit.push({at:new Date().toISOString(),action:String(action).slice(0,100)});next.audit=next.audit.slice(-500);await write(await encrypt(next));current=next;return structuredClone(current)});
export const lock=()=>serial(async()=>{key=null;salt=null;current=null;release?.();release=null});
export const backup=()=>serial(async()=>{if(!key)throw Error('저장소를 먼저 열어주세요.');return encrypt(current)});
export const restore=(envelope,password)=>serial(async()=>{await acquire();try{const r=await decrypt(envelope,password);await write(await encrypt(r.data,r.key,r.salt));key=r.key;salt=r.salt;current=r.data;return structuredClone(current)}catch(e){if(!key){release?.();release=null}throw e}});
